import { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  {
    id: "cafe-ordering",
    title: "Cafe Ordering",
    titleKo: "카페 주문",
    emoji: "☕",
    description: "Order your favorite coffee and pastry at a cozy cafe",
    aiRole: "barista",
    location: "a cozy neighborhood cafe",
    situation: "Customer walks in to order a drink and a snack",
    expectedFlow: "Greeting → Take order → Ask customization → Confirm → Payment → Farewell",
    difficulty: "beginner",
    initialMessage: "Hi there! Welcome to Sunrise Cafe. What can I get started for you today?",
  },
  {
    id: "airport-checkin",
    title: "Airport Check-in",
    titleKo: "공항 체크인",
    emoji: "✈️",
    description: "Check in for your international flight at the airport counter",
    aiRole: "airline check-in agent",
    location: "an international airport check-in counter",
    situation: "Passenger approaches the counter to check in for a flight",
    expectedFlow: "Greeting → Passport/booking → Luggage → Seat preference → Boarding pass → Gate info",
    difficulty: "intermediate",
    initialMessage: "Good morning! Welcome to SkyLine Airlines. May I see your passport and booking confirmation, please?",
  },
  {
    id: "shopping-clothes",
    title: "Clothes Shopping",
    titleKo: "옷 쇼핑",
    emoji: "👔",
    description: "Find the perfect outfit with help from a store assistant",
    aiRole: "clothing store sales assistant",
    location: "a clothing retail store",
    situation: "Customer looking for a specific item or browsing",
    expectedFlow: "Greeting → What looking for → Size/color → Try on → Feedback → Purchase decision",
    difficulty: "beginner",
    initialMessage: "Hello! Welcome to Urban Style. Are you looking for anything in particular today, or just browsing?",
  },
  {
    id: "hotel-checkin",
    title: "Hotel Check-in",
    titleKo: "호텔 체크인",
    emoji: "🏨",
    description: "Check into your hotel and ask about amenities",
    aiRole: "hotel front desk receptionist",
    location: "a hotel front desk",
    situation: "Guest arrives to check in to their reserved room",
    expectedFlow: "Greeting → Reservation lookup → Room details → Amenities → Key card → Enjoy stay",
    difficulty: "intermediate",
    initialMessage: "Good afternoon! Welcome to The Grand Hotel. Do you have a reservation with us?",
  },
  {
    id: "restaurant-dining",
    title: "Restaurant Dining",
    titleKo: "레스토랑 식사",
    emoji: "🍽️",
    description: "Have a full dining experience from ordering to paying the bill",
    aiRole: "restaurant waiter/waitress",
    location: "a mid-range restaurant",
    situation: "Diner seated and ready to order",
    expectedFlow: "Greeting → Menu/specials → Order food/drinks → Check on meal → Dessert → Bill",
    difficulty: "beginner",
    initialMessage: "Good evening! Welcome to Bella's. Here are your menus. Can I start you off with something to drink?",
  },
];
